import { AchievementsSectionType } from '../types/sections';

export const achievementsSection: AchievementsSectionType = {
  title: 'Awards & Achievements',
  achievements: [
    {
      title: 'Module 1: Personal & Professional Development Badge',
      date: 'September 2025',
      issuer: 'Aspire Institute Leadership Program',
      desc: 'Achieved professional development badge for completing leadership module.',
    },
    {
      title: 'Professional Internship Certificate',
      date: 'July 2025',
      issuer: 'Robo Tech Valley',
      desc: 'Successful completion of professional internship program in Robotics and Embedded Systems.',
      certificate: '/certificates/Ratul Internship Certificate.png',
    },
    {
      title: 'Dean’s Award & Dean’s List',
      date: 'June 29, 2025',
      issuer: 'University of Frontier Technology, Bangladesh',
      desc: 'Recognized for outstanding academic performance and earned the prestigious Dean’s Award during Level-3.',
      certificate: '/certificates/Dean\'s List Award (Level-3).jpg',
    },
    {
      title: 'RTV Organizing Team Member',
      date: 'June 2025',
      issuer: '5th International Robotic Olympiad Organizing Committee',
      desc: 'Active participation as an organizing committee member for a prestigious international robotics event.',
      certificate: '/certificates/RTV Oraganizing Team Member .png',
    },
    {
      title: 'OPSWAT Critical Infrastructure Protection',
      date: 'February 2025',
      issuer: 'OPSWAT',
      desc: 'Professional certification in critical infrastructure cybersecurity and defense.',
      certificate: '/certificates/7. OPSWAT CIP Certificate.png',
    },
    {
      title: 'Advanced Cybersecurity Program Certificate',
      date: 'March 15, 2025',
      issuer: 'Team Matrix Elite Hackers',
      desc: 'Completed comprehensive cybersecurity training program covering advanced techniques.',
      certificate: '/certificates/6. Team Matrix Certificate.jpg',
    },
    {
      title: 'Winner – Applink Innovative Idea Contest',
      date: 'February 2024',
      issuer: 'Applink',
      desc: 'Won first place with the innovative concept of "Intelligent Law Advisor App" in a national competition.',
    },
    {
      title: '21st Century Employability Skilling (Advanced)',
      date: 'December 2023',
      issuer: 'Wadhwani Foundation',
      desc: 'Advanced certification in modern workplace skills and professional development.',
      certificate: '/certificates/5. Soft Skill Certificate.pdf',
    },
    {
      title: '21st Century Employability Skilling Developer Program',
      date: 'October 2023',
      issuer: 'Wadhwani Foundation',
      desc: 'Developer employability soft skill certification in modern workplace skills.',
      certificate: '/certificates/3. Soft Skill (Core Employability).jpg',
    },
    {
      title: 'Cyber Security Training Certificate',
      date: 'October 2023',
      issuer: 'Creative IT Institute',
      desc: 'Specialized training in cybersecurity defense protocols and practices.',
      certificate: '/certificates/4. Creative IT Certificate.jpg',
    },
    {
      title: 'AWS Introduction to Cloud Certificate',
      date: 'August 16, 2023',
      issuer: 'AWS Academy',
      desc: 'Comprehensive cloud computing certification covering AWS fundamentals.',
      certificate: '/certificates/2. AWS Crtificate.pdf',
    },
    {
      title: '3rd Runner Up – Upazila Science Fair',
      date: 'May 2023',
      issuer: 'Chandra, Gazipur',
      desc: 'Recognized for innovative project presentation at the regional science fair.',
    },
    {
      title: 'Python Programming Certificate',
      date: 'January 2022',
      issuer: 'CPP Buzz',
      desc: 'Comprehensive Python programming skills certification from basic to advanced levels.',
      certificate: '/certificates/1. CPP Buzz Certificate.pdf',
    },
  ],
};
