import { ProjectsSectionType } from '../types/sections';

export const projectsSection: ProjectsSectionType = {
  title: 'Other Notable Projects',
  projects: [
    {
      id: 'vwar',
      name: 'BITSS VWAR Software (Windows & Portable)',
      category: 'software security',
      url: 'https://bitss.one/',
      repo: 'https://github.com/TM-Mehrab-Hasan/BITSS-VWAR-Software',
      year: 2025,
      img: '/images/projects/bitss.png',
      mainIcon: 'akar-icons:shield',
      color: '#2563eb', // Blue
      projectSkills: [
        { name: 'Python', icon: 'logos:python' },
        { name: 'Security', icon: 'mdi:security' },
        { name: 'Malware Detection', icon: 'mdi:shield-check' },
        { name: 'Desktop App', icon: 'mdi:monitor' },
      ],
      description: 'Enterprise device security software providing malware filtering, identification, neutralization and removal. Supports both offline and online modes for comprehensive protection.',
    },
    {
      id: 'baazar-x',
      name: 'BAAZAR X - AI-Powered E-Commerce Platform',
      category: 'web ml',
      url: 'https://baazarx.netlify.app/',
      repo: 'https://github.com/TM-Mehrab-Hasan/baazarx-ai-ecommerce',
      year: 2025,
      img: '/images/projects/baazar-x.png',
      mainIcon: 'akar-icons:shopping-bag',
      color: '#9333ea', // Purple
      projectSkills: [
        { name: 'Django', icon: 'logos:django-icon' },
        { name: 'AI Chatbot', icon: 'mdi:robot-happy' },
        { name: 'E-Commerce', icon: 'mdi:cart' },
        { name: 'Python', icon: 'logos:python' },
      ],
      description: 'Modern AI-powered e-commerce platform featuring clean white design with neon blue accents, intelligent chatbot assistance, comprehensive product management, and complete admin dashboard.',
    },
    {
      id: 'fire-robot',
      name: 'Early Stage Fire Detection Robot',
      category: 'iot robotics',
      url: '#',
      repo: 'https://github.com/TM-Mehrab-Hasan/Early-Stage-Fire-Detection-Robot',
      year: 2023,
      img: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
      mainIcon: 'akar-icons:fire',
      color: '#ef4444', // Red
      projectSkills: [
        { name: 'Arduino', icon: 'logos:arduino' },
        { name: 'IoT Sensors', icon: 'mdi:sensor' },
        { name: 'Wireless Control', icon: 'mdi:wifi' },
        { name: 'Real-time Alerts', icon: 'mdi:bell-ring' },
      ],
      description: 'An autonomous robot for fire detection with automated water sprinkler, wireless control, and real-time alerts. Featured at 57th International Education Expo 2023.',
    },
    {
      id: 'movie',
      name: 'Movie Website',
      category: 'web',
      url: 'https://cinemavault.netlify.app/',
      repo: 'https://github.com/TM-Mehrab-Hasan/CineVault_Movie_Website',
      year: 2024,
      img: '/images/projects/cinemavault.png',
      mainIcon: 'akar-icons:video',
      color: '#f97316', // Orange
      projectSkills: [
        { name: 'JavaScript', icon: 'logos:javascript' },
        { name: 'HTML5', icon: 'logos:html-5' },
        { name: 'CSS3', icon: 'logos:css-3' },
        { name: 'API Integration', icon: 'mdi:api' },
      ],
      description: 'A comprehensive movie discovery platform with advanced search functionality, user reviews, and personalized recommendations.',
    },
    {
      id: 'fake-news',
      name: 'Fake News Detection System',
      category: 'ml',
      url: '#',
      repo: 'https://github.com/TM-Mehrab-Hasan/Fake-News-Detection',
      year: 2024,
      img: 'https://images.unsplash.com/photo-1591115765373-520b7a21f7d5?auto=format&fit=crop&w=800&q=80',
      mainIcon: 'akar-icons:newspaper',
      color: '#10b981', // Green
      projectSkills: [
        { name: 'Python', icon: 'logos:python' },
        { name: 'NLP', icon: 'mdi:brain' },
        { name: 'Scikit-learn', icon: 'logos:scikit-learn' },
        { name: 'Jupyter', icon: 'logos:jupyter' },
      ],
      description: 'Machine learning-based system for detecting and classifying fake news using natural language processing and advanced ML algorithms.',
    },
    {
      id: 'gps-tracker',
      name: 'Real-Time GPS Location Tracker',
      category: 'iot',
      url: '#',
      repo: 'https://github.com/TM-Mehrab-Hasan/Real-Time-Location-Tracker-Using-U-Blox-Neo-6m-GPS-Sensor-with-ESP8266',
      year: 2024,
      img: '/images/projects/gps.png',
      mainIcon: 'akar-icons:location',
      color: '#3b82f6', // Light Blue
      projectSkills: [
        { name: 'ESP8266', icon: 'logos:esp32' },
        { name: 'GPS Sensor', icon: 'mdi:map-marker' },
        { name: 'C++', icon: 'logos:c-plusplus' },
        { name: 'Real-time Data', icon: 'mdi:database-sync' },
      ],
      description: 'IoT-based location tracking system using U-Blox Neo-6m GPS sensor with ESP8266 for real-time location monitoring and data transmission.',
    },
    {
      id: 'water-monitor',
      name: 'Real-Time Water Quality Monitor',
      category: 'iot',
      url: '#',
      repo: 'https://github.com/TM-Mehrab-Hasan/Real-Time-Water-Quality-Monitor-Using-ESP32-with-Local-Server',
      year: 2024,
      img: '/images/projects/water.png',
      mainIcon: 'akar-icons:water',
      color: '#06b6d4', // Cyan
      projectSkills: [
        { name: 'ESP32', icon: 'logos:esp32' },
        { name: 'Water Sensors', icon: 'mdi:water' },
        { name: 'Local Server', icon: 'mdi:server' },
        { name: 'C++', icon: 'logos:c-plusplus' },
      ],
      description: 'ESP32-based water quality monitoring system with local server integration for real-time analysis of pH, turbidity, and other water parameters.',
    },
    {
      id: 'portfolio-v1',
      name: 'Modern Portfolio Website',
      category: 'web',
      url: 'https://tm-mehrab-hasan.github.io',
      repo: 'https://github.com/TM-Mehrab-Hasan/TM-Mehrab-Hasan.github.io',
      year: 2025,
      img: '/images/projects/portfolio-v1.png',
      mainIcon: 'akar-icons:desktop-device',
      color: '#6366f1', // Indigo
      projectSkills: [
        { name: 'Three.js', icon: 'logos:threejs' },
        { name: 'CSS3', icon: 'logos:css-3' },
        { name: 'JavaScript', icon: 'logos:javascript' },
        { name: 'Responsive Design', icon: 'mdi:responsive' },
      ],
      description: 'Cutting-edge portfolio website with 3D animations, glassmorphism design, and advanced interactive features built with modern web technologies.',
    },
    {
      id: 'drainage-system',
      name: 'Smart Drainage Congestion Management',
      category: 'iot ml',
      url: '#',
      repo: '#',
      year: 2024,
      img: '/images/projects/drainage.png',
      mainIcon: 'akar-icons:water',
      color: '#475569', // Slate
      projectSkills: [
        { name: 'Machine Learning', icon: 'mdi:brain' },
        { name: 'Mobile App', icon: 'mdi:cellphone' },
        { name: 'IoT Sensors', icon: 'mdi:sensor' },
        { name: 'Real-time Monitoring', icon: 'mdi:chart-timeline-variant' },
      ],
      description: "IoT-based system for garbage detection using ML with automated water-flow control and real-time monitoring for Bangladesh's drainage systems.",
    },
    {
      id: 'investment-advisor',
      name: 'Intelligent Investment Advisor AI',
      category: 'ml',
      url: '#',
      repo: 'https://github.com/TM-Mehrab-Hasan/Investment_Sector_Recommendation',
      year: 2024,
      img: '/images/projects/investment.png',
      mainIcon: 'akar-icons:statistic',
      color: '#f59e0b', // Yellow
      projectSkills: [
        { name: 'Deep Learning', icon: 'mdi:robot-mop' },
        { name: 'Explainable AI', icon: 'mdi:eye-check' },
        { name: 'Python', icon: 'logos:python' },
        { name: 'Data Analysis', icon: 'mdi:chart-bar' },
      ],
      description: 'Stacked ML-based system for investment recommendations with Explainable AI providing clear reasoning for investment decisions.',
    },
    {
      id: 'greenity',
      name: 'Greenity Foundation Platform',
      category: 'web',
      url: 'https://greenityfoundation.vercel.app/',
      repo: '#',
      year: '2022-2023',
      img: '/images/projects/greenity.png',
      mainIcon: 'akar-icons:leaf',
      color: '#16a34a', // Green
      projectSkills: [
        { name: 'React JS', icon: 'logos:react' },
        { name: 'Node.js', icon: 'logos:nodejs-icon' },
        { name: 'Database', icon: 'mdi:database' },
        { name: 'API Integration', icon: 'mdi:api' },
      ],
      description: 'Led development of responsive website platforms for environmental foundation, integrating backend databases and APIs for enhanced functionality.',
    },
    {
      id: 'robotics-course',
      name: 'Robotics Course Development',
      category: 'robotics',
      url: '#',
      repo: '#',
      year: 2025,
      img: '/images/projects/robotics-course.png',
      mainIcon: 'akar-icons:book',
      color: '#ec4899', // Pink
      projectSkills: [
        { name: 'Embedded Systems', icon: 'mdi:chip' },
        { name: 'Arduino', icon: 'logos:arduino' },
        { name: 'Course Design', icon: 'mdi:book-open-variant' },
        { name: 'Education', icon: 'mdi:school' },
      ],
      description: 'Comprehensive robotics projects and educational courses focusing on embedded systems, automation, and real-world applications.',
    },
  ],
};
