import { SkillsSectionType } from '../types/sections';

export const skillsSection: SkillsSectionType = {
  title: 'Skills & Technologies',
  skills: [
    {
      id: 'fullstack',
      title: 'Software Development',
      lottie: {
        light: '/lotties/frontend.json',
        dark: '/lotties/frontend-dark.json',
      },
      points: [
        'Building responsive Single-Page-Apps (SPA) using React.js and Next.js',
        'Developing robust backend systems using Django, Python, and PHP',
        'Managing relational and NoSQL databases like PostgreSQL, MySQL, and MongoDB',
        'Implementing RESTful APIs and real-time communication systems',
      ],
      projectSkills: [
        { name: 'Python', icon: 'logos:python' },
        { name: 'Django', icon: 'logos:django-icon' },
        { name: 'JavaScript', icon: 'logos:javascript' },
        { name: 'TypeScript', icon: 'logos:typescript-icon' },
        { name: 'React', icon: 'logos:react' },
        { name: 'Next.js', icon: 'logos:nextjs-icon' },
        { name: 'PHP', icon: 'logos:php' },
        { name: 'MySQL', icon: 'logos:mysql' },
        { name: 'MongoDB', icon: 'logos:mongodb-icon' },
      ],
    },
    {
      id: 'robotics',
      title: 'Robotics & IoT Engineering',
      lottie: {
        light: '/lotties/designing.json',
        dark: '/lotties/designing-dark.json',
      },
      points: [
        'Designing autonomous robots using ROS (Robot Operating System) and Arduino',
        'Developing firmware for embedded systems in C/C++',
        'Implementing IoT solutions with real-time monitoring and cloud integration (Firebase)',
        'Engineering intelligent sensing technologies for industrial applications',
      ],
      projectSkills: [
        { name: 'C++', icon: 'logos:c-plusplus' },
        { name: 'Arduino', icon: 'logos:arduino' },
        { name: 'Raspberry Pi', icon: 'logos:raspberry-pi' },
        { name: 'ESP32', icon: 'logos:esp32' },
        { name: 'Firebase', icon: 'logos:firebase' },
        { name: 'ROS', icon: 'logos:ros' },
      ],
    },
    {
      id: 'tools',
      title: 'Tools & DevOps',
      lottie: {
        light: '/lotties/404.json',
        dark: '/lotties/404.json',
      },
      points: [
        'Version control and collaborative development using Git and GitHub',
        'Working with Linux-based systems and terminal environments',
        'Containerization and deployment strategies',
      ],
      projectSkills: [
        { name: 'Git', icon: 'logos:git-icon' },
        { name: 'GitHub', icon: 'logos:github-icon' },
        { name: 'Linux', icon: 'logos:linux-tux' },
        { name: 'Docker', icon: 'logos:docker-icon' },
        { name: 'Vercel', icon: 'logos:vercel-icon' },
      ],
    },
  ],
  softwareSkills: [
    {
      name: 'HTML5',
      icon: 'logos:html-5',
      level: 95,
      experience: '5+ years',
      description: 'Semantic markup, accessibility, modern HTML5 APIs',
      category: 'frontend',
      featured: true,
    },
    {
      name: 'CSS3',
      icon: 'logos:css-3',
      level: 93,
      experience: '5+ years',
      description: 'Animations, Grid, Flexbox, Responsive Design',
      category: 'frontend',
    },
    {
      name: 'JavaScript',
      icon: 'logos:javascript',
      level: 90,
      experience: '4+ years',
      description: 'ES6+, DOM manipulation, Async programming',
      category: 'frontend',
      featured: true,
    },
    {
      name: 'React',
      icon: 'logos:react',
      level: 80,
      experience: '2+ years',
      description: 'Hooks, Context API, Component architecture',
      category: 'frontend',
      featured: true,
    },
    {
      name: 'Next.js',
      icon: 'logos:nextjs-icon',
      level: 85,
      experience: '2+ years',
      description: 'App Router, SSR, SSG, API Routes',
      category: 'frontend',
      featured: true,
    },
    {
      name: 'Python',
      icon: 'logos:python',
      level: 95,
      experience: '4+ years',
      description: 'Django, Flask, Data Science, Automation',
      category: 'backend',
      featured: true,
    },
    {
      name: 'Django',
      icon: 'logos:django-icon',
      level: 88,
      experience: '2+ years',
      description: 'REST APIs, Authentication, ORM',
      category: 'backend',
      featured: true,
    },
    {
      name: 'C/C++',
      icon: 'logos:c-plusplus',
      level: 90,
      experience: '4+ years',
      description: 'System programming, Embedded systems',
      category: 'backend',
    },
    {
      name: 'PHP',
      icon: 'logos:php',
      level: 92,
      experience: '3+ years',
      description: 'Web development, Database integration',
      category: 'backend',
      featured: true,
    },
    {
      name: 'MySQL',
      icon: 'logos:mysql',
      level: 90,
      experience: '3+ years',
      description: 'Query optimization, Database design',
      category: 'backend',
      featured: true,
    },
    {
      name: 'MongoDB',
      icon: 'logos:mongodb-icon',
      level: 82,
      experience: '2+ years',
      description: 'NoSQL, Aggregation, Document design',
      category: 'backend',
    },
    {
      name: 'Firebase',
      icon: 'logos:firebase',
      level: 90,
      experience: '2+ years',
      description: 'Realtime database, Authentication, Hosting',
      category: 'backend',
    },
    {
      name: 'Arduino',
      icon: 'logos:arduino',
      level: 93,
      experience: '3+ years',
      description: 'Sensors, Actuators, IoT prototyping',
      category: 'iot',
      featured: true,
    },
    {
      name: 'Embedded Systems',
      icon: 'mdi:robot-industrial',
      level: 92,
      experience: '3+ years',
      description: 'Microcontrollers, Real-time systems',
      category: 'iot',
      featured: true,
    },
    {
      name: 'IoT Integration',
      icon: 'mdi:wifi',
      level: 95,
      experience: '3+ years',
      description: 'Wireless protocols, Cloud integration',
      category: 'iot',
      featured: true,
    },
    {
      name: 'Wireless System Integration',
      icon: 'mdi:antenna',
      level: 90,
      experience: '3+ years',
      description: 'RF communication, wireless sensor networks',
      category: 'iot',
      featured: true,
    },
    {
      name: 'Git',
      icon: 'logos:git-icon',
      level: 90,
      experience: '2+ years',
      description: 'Version control, Collaboration',
      category: 'tools',
    },
    {
      name: 'GitHub',
      icon: 'logos:github-icon',
      level: 92,
      experience: '2+ years',
      description: 'CI/CD, actions, collaboration',
      category: 'tools',
    },
    {
      name: 'Jira',
      icon: 'logos:jira',
      level: 85,
      experience: '1+ year',
      description: 'Project management, Agile, Scrum',
      category: 'tools',
    },
    {
      name: 'Google Cloud Platform',
      icon: 'logos:google-cloud',
      level: 80,
      experience: '1+ year',
      description: 'Cloud hosting, App Engine, Compute Engine',
      category: 'tools',
    },
    {
      name: 'Linux',
      icon: 'logos:linux-tux',
      level: 80,
      experience: '2+ years',
      description: 'System administration, Shell scripting',
      category: 'tools',
    },
  ],
};
